apiVersion: v1
kind: Namespace
metadata:
  name: silly-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-app
  namespace: silly-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silly-app
  template:
    metadata:
      labels:
        app: silly-app
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: silly-app
  namespace: silly-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: silly-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: silly-app-ingress
  namespace: silly-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: silly-app.team-a.mycompany.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: silly-app
            port:
              number: 80
